In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
x = [8.0, 1, 2.5, 4., 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4., 28.0]

print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4.0, 28.0]
[8.0, 1, 2.5, nan, 4.0, 28.0]


In [3]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

print(y)
print(y_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]


In [4]:
print(z)
print(z_with_nan)

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


# Measures of Central Tendency

## Mean

In [5]:
mean_ = sum(x) / len(x)
mean_

8.7

In [6]:
mean_ = statistics.mean(x)
mean_

8.7

In [7]:
mean_ = statistics.mean(x_with_nan)
mean_

nan

In [8]:
sum(x_with_nan)

nan

In [9]:
mean_ = np.mean(y)
mean_

8.7

In [10]:
mean_ = y.mean()
mean_

8.7

In [11]:
np.mean(y_with_nan)

nan

In [12]:
y_with_nan.mean()

nan

In [13]:
np.nanmean(y_with_nan) #mengabaikan nilai nan

8.7

In [14]:
z #pandas series

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64

In [15]:
z.mean()

8.7

In [16]:
z_with_nan.mean()

8.7

## Weighted Mean

In [17]:
var = [2, 2, 4, 4, 4, 4, 4, 8, 8, 8]
len(var)

10

In [18]:
(0.2 * 2) + (0.5 * 4) + (0.3 * 8)

4.8

In [19]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]

In [20]:
sum(w)

1.0

In [21]:
wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
wmean

6.95

In [22]:
wmean = sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
wmean

6.95

In [23]:
y, z, w = np.array(x), pd.Series(x), np.array(w)

wmean = np.average(y, weights=w)
wmean

6.95

In [24]:
np.average(z, weights=w)

6.95

In [25]:
(w * y).sum() / w.sum()

6.95

## Harmonic Mean

In [26]:
(60 + 20)/2

40.0

In [27]:
(2+4+6+100)/4

28.0

In [28]:
4 / (1/2 + 1/4 + 1/6 + 1/100) #handling outlier yg besar sehingga average tidak menjauh dr data asli

4.316546762589928

In [29]:
statistics.harmonic_mean(x)

2.7613412228796843

In [30]:
np.mean(x)

8.7

In [31]:
x

[8.0, 1, 2.5, 4, 28.0]

In [32]:
scipy.stats.hmean(y)

2.7613412228796843

In [33]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [34]:
scipy.stats.hmean(z)

2.7613412228796843

## Geometric Mean

In [35]:
# Geometric mean berguna ketika kita ingin membandingkan berbagai hal dengan properti yang sangat berbeda

In [36]:
2 * 18

36

In [37]:
gmean = 1

for item in x:
    gmean *= item
    
# gmean **= 1 / len(x)
gmean

2240.0

In [38]:
gmean **= 1 / len(x)
gmean

4.677885674856041

In [39]:
scipy.stats.gmean(y)

4.67788567485604

In [40]:
scipy.stats.gmean(z)

4.67788567485604

## Median

In [41]:
n = len(x)
if n % 2:
    median_ = sorted(x)[round(0.5 * (n-1))]
else:
    x_ord, index = sorted(x), round(0.5 * n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])
    
median_

4

In [42]:
statistics.median_low(x[:-1])

2.5

In [43]:
statistics.median_high(x[:-1])

4

In [44]:
statistics.median_high(x_with_nan)

8.0

In [45]:
np.median(y)

4.0

In [46]:
np.median(y[:-1])

3.25

## Mode

In [47]:
u = [2, 3, 2, 8, 12]

v = [12, 15, 12, 15, 21, 15, 12]

mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

2

In [48]:
statistics.mode(u)

2

In [49]:
u, v = np.array(u), np.array(v)
scipy.stats.mode(u)

ModeResult(mode=array([2]), count=array([2]))

In [50]:
scipy.stats.mode(v).count

array([3])

In [51]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

In [52]:
u.mode()

0    2
dtype: int32

In [53]:
v.mode()

0    12
1    15
dtype: int32

In [54]:
w.mode()

0    2.0
dtype: float64

# Measures of Variability

In [55]:
n = len(x)

mean_ = sum(x) / n

var_ = sum((item - mean_)**2 for item in x) / (n-1)
var_

123.19999999999999

In [56]:
statistics.variance(x)

123.2

In [57]:
np.var(y, ddof=1)

123.19999999999999

In [58]:
y.var(ddof=1)

123.19999999999999

In [59]:
z

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64

In [60]:
z.var(ddof=1)

123.19999999999999

## Standard Deviation

In [61]:
std_ = var_ ** 0.5
std_

11.099549540409285

In [62]:
statistics.stdev(x)

11.099549540409287

In [63]:
np.std(y, ddof=1)

11.099549540409285

In [64]:
y.std(ddof=1)

11.099549540409285

## Skewness

In [65]:
x

[8.0, 1, 2.5, 4, 28.0]

In [66]:
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n-1)
std_ = var_ ** 0.5

skew_ = (sum((item - mean_)**3 for item in x) * n / ((n-1) * (n-2) * std_**3))
skew_

1.9470432273905929

In [67]:
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [68]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [69]:
z.skew()

1.9470432273905924

In [70]:
z_with_nan.skew()

1.9470432273905924

## Percentiles

In [138]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]
x

[-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]

In [72]:
statistics.quantiles(x, n=2)

[8.0]

In [73]:
statistics.quantiles(x, n=4, method='inclusive')

[0.1, 8.0, 21.0]

In [139]:
y = np.array(x)

In [75]:
np.percentile(y, 95)

34.919999999999995

In [76]:
np.percentile(y, 50)

8.0

In [77]:
y_with_nan = np.insert(y, 2, np.nan)
y_with_nan

array([-5. , -1.1,  nan,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [78]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [79]:
z, z_with_nan = pd.Series(y), pd.Series(y_with_nan)

In [80]:
z.quantile(0.05)

-3.44

In [81]:
z.quantile([0.25, 0.50, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [82]:
z_with_nan.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

## Range

In [83]:
np.ptp(y)

46.0

In [84]:
sorted(y)

[-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]

In [85]:
41 - (-5)

46

In [86]:
np.ptp(z)

46.0

In [87]:
np.ptp(y_with_nan)

nan

In [88]:
np.ptp(z_with_nan)

nan

In [140]:
np.amax(y) - np.amin(y)

46.0

In [133]:
np.nanmax(y_with_nan) - np.nanmin(y_with_nan)

46.0

In [141]:
y.max() - y.min()

46.0

In [142]:
z.max() - z.min()

46.0

In [143]:
z_with_nan.max() - z_with_nan.min()

46.0

## Summary of Desc Stat

In [89]:
result = scipy.stats.describe(y, ddof=1, bias=False)
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [90]:
result.nobs

9

In [91]:
result.minmax[1] # Max

41.0

In [92]:
result.minmax[0] # Min

-5.0

In [93]:
result.skewness

0.9249043136685094

In [94]:
result = z.describe()
result

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

In [95]:
result['mean']

11.622222222222222

In [96]:
result['25%']

0.1

# Correlation

In [144]:
x = list(range(-10, 11))
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]

In [145]:
x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x), pd.Series(y)

## Covariance

In [146]:
n = len(x)
mean_x, mean_y = sum(x) / n, sum(y) / n

cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) for k in range(n)) / (n-1))
cov_xy

19.95

In [100]:
np.cov(x_, y_)

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [101]:
x_.var(ddof=1)

38.5

In [102]:
y_.var(ddof=1)

13.914285714285711

In [103]:
cov_xy = np.cov(x_, y_)[0,1]
cov_xy

19.95

## Correlation Coefficient

In [147]:
var_x = sum((item - mean_x)**2 for item in x) / (n-1)
var_y = sum((item - mean_y)**2 for item in y) / (n-1)

std_x, std_y = var_x**0.5, var_y**0.5

r = cov_xy / (std_x * std_y)
r

0.861950005631606

In [105]:
scipy.stats.pearsonr(x_, y_)

(0.8619500056316058, 5.122760847201207e-07)

In [106]:
np.corrcoef(x_, y_)

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [107]:
np.corrcoef(x_, y_)[0,1]

0.8619500056316061

In [108]:
scipy.stats.linregress(x_, y_)

LinregressResult(slope=0.5181818181818181, intercept=5.714285714285714, rvalue=0.861950005631606, pvalue=5.122760847201164e-07, stderr=0.06992387660074979, intercept_stderr=0.4234100995002589)

In [109]:
scipy.stats.linregress(x_, y_).rvalue

0.861950005631606

In [110]:
x__.corr(y__)

0.8619500056316061

In [111]:
y__.corr(x__)

0.861950005631606

# 2D Data

In [112]:
a = np.array([[1,1,1],
             [2,3,1],
             [4,9,2],
             [8,27,4],
             [16,1,1]])

a

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [113]:
np.mean(a)

5.4

In [114]:
a.mean()

5.4

In [115]:
np.median(a)

2.0

In [116]:
np.mean(a, axis=0)

array([6.2, 8.2, 1.8])

In [117]:
np.mean(a, axis=1) #a.mean(axis=1)

array([ 1.,  2.,  5., 13.,  6.])

In [118]:
scipy.stats.gmean(a)

array([4.        , 3.73719282, 1.51571657])

In [119]:
scipy.stats.gmean(a, axis=1)

array([1.        , 1.81712059, 4.16016765, 9.52440631, 2.5198421 ])

In [120]:
scipy.stats.gmean(a, axis=None)

2.829705017016332

In [121]:
scipy.stats.describe(a, axis=None, ddof=1, bias=False)

DescribeResult(nobs=15, minmax=(1, 27), mean=5.4, variance=53.40000000000001, skewness=2.264965290423389, kurtosis=5.212690982795767)

# Dataframe

In [122]:
row_names = ['first', 'second', 'third', 'fourth', 'fifth']
col_names = ['A', 'B', 'C']

df = pd.DataFrame(a, index=row_names, columns=col_names)
df

A   B  C
first    1   1  1
second   2   3  1
third    4   9  2
fourth   8  27  4
fifth   16   1  1

In [123]:
df.mean()

A    6.2
B    8.2
C    1.8
dtype: float64

In [124]:
df.var()

A     37.2
B    121.2
C      1.7
dtype: float64

In [125]:
df.mean(axis=1)

first      1.0
second     2.0
third      5.0
fourth    13.0
fifth      6.0
dtype: float64

In [126]:
df['A']

first      1
second     2
third      4
fourth     8
fifth     16
Name: A, dtype: int32

In [127]:
df['A'].var()

37.20000000000001

In [128]:
df.values

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [129]:
df.to_numpy()

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [130]:
df.describe()

A          B        C
count   5.00000   5.000000  5.00000
mean    6.20000   8.200000  1.80000
std     6.09918  11.009087  1.30384
min     1.00000   1.000000  1.00000
25%     2.00000   1.000000  1.00000
50%     4.00000   3.000000  1.00000
75%     8.00000   9.000000  2.00000
max    16.00000  27.000000  4.00000

In [131]:
df.describe().at['mean', 'A']

6.2